UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Desarrollo Rural ', "vNombreCorto" = 'SEDER' WHERE "iIdDependencia" = 1;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Fomento Económico y Trabajo ', "vNombreCorto" = 'SEFOET' WHERE "iIdDependencia" = 2;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Fomento Turístico ', "vNombreCorto" = 'SEFOTUR' WHERE "iIdDependencia" = 3;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Pesca y Acuacultura Sustentables ', "vNombreCorto" = 'SEPASY' WHERE "iIdDependencia" = 4;
UPDATE "Dependencia" SET "vDependencia" = 'Aeropuerto de Chichen Itzá del Estado de Yucatán', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 5;
UPDATE "Dependencia" SET "vDependencia" = 'Agencia para el Desarrollo de Yucatán ', "vNombreCorto" = 'ADY' WHERE "iIdDependencia" = 6;
UPDATE "Dependencia" SET "vDependencia" = 'Fideicomiso Público para el Desarrollo del Turismo de Reuniones en Yucatán ', "vNombreCorto" = 'FIDETURE' WHERE "iIdDependencia" = 7;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Capacitación para el Trabajo del Estado de Yucatán ', "vNombreCorto" = 'ICATEY' WHERE "iIdDependencia" = 8;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Promotor de Ferias de Yucatán ', "vNombreCorto" = 'IPFY' WHERE "iIdDependencia" = 9;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Yucateco de Emprendedores ', "vNombreCorto" = 'IYEM' WHERE "iIdDependencia" = 10;
UPDATE "Dependencia" SET "vDependencia" = 'Patronato de las Unidades de Servicios Culturales y Turísticos del Estado de Yucatán ', "vNombreCorto" = 'CULTUR' WHERE "iIdDependencia" = 11;
UPDATE "Dependencia" SET "vDependencia" = 'Empresa Portuaria de Yucatán ', "vNombreCorto" = 'EPY' WHERE "iIdDependencia" = 12;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Desarrollo Social ', "vNombreCorto" = 'SEDESOL' WHERE "iIdDependencia" = 13;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Salud ', "vNombreCorto" = 'SSY' WHERE "iIdDependencia" = 14;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Educación del Gobierno del Estado de Yucatán ', "vNombreCorto" = 'SEGEY' WHERE "iIdDependencia" = 15;
UPDATE "Dependencia" SET "vDependencia" = 'Administración del Patrimonio de la Beneficencia Pública del Estado de Yucatán ', "vNombreCorto" = 'APBPY' WHERE "iIdDependencia" = 16;
UPDATE "Dependencia" SET "vDependencia" = 'Centro Estatal de Trasplantes de Yucatán ', "vNombreCorto" = 'CEETRY' WHERE "iIdDependencia" = 17;
UPDATE "Dependencia" SET "vDependencia" = 'Colegio de Bachilleres del Estado de Yucatán ', "vNombreCorto" = 'COBAY' WHERE "iIdDependencia" = 18;
UPDATE "Dependencia" SET "vDependencia" = 'Colegio de Educación Profesional Técnica del Estado de Yucatán ', "vNombreCorto" = 'CONALEP' WHERE "iIdDependencia" = 19;
UPDATE "Dependencia" SET "vDependencia" = 'Colegio de Estudios Científicos y Tecnológicos del Estado de Yucatán ', "vNombreCorto" = 'CECYTEY' WHERE "iIdDependencia" = 20;
UPDATE "Dependencia" SET "vDependencia" = 'Hospital Comunitario de Peto, Yucatán ', "vNombreCorto" = 'HCPY' WHERE "iIdDependencia" = 21;
UPDATE "Dependencia" SET "vDependencia" = 'Hospital Comunitario de Ticul, Yucatán ', "vNombreCorto" = 'HCTY' WHERE "iIdDependencia" = 22;
UPDATE "Dependencia" SET "vDependencia" = 'Hospital de la Amistad Corea-México ', "vNombreCorto" = 'HA' WHERE "iIdDependencia" = 23;
UPDATE "Dependencia" SET "vDependencia" = 'Hospital General de Tekax', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 24;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Becas y Crédito Educativo del Estado de Yucatán ', "vNombreCorto" = 'IBECEY' WHERE "iIdDependencia" = 25;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Educación para Adultos del Estado de Yucatán ', "vNombreCorto" = 'IEAEY' WHERE "iIdDependencia" = 26;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto para el Desarrollo de la Cultura Maya del Estado de Yucatán ', "vNombreCorto" = 'INDEMAYA' WHERE "iIdDependencia" = 27;
UPDATE "Dependencia" SET "vDependencia" = 'Junta de Asistencia Privada del Estado de Yucatán ', "vNombreCorto" = 'JAPEY' WHERE "iIdDependencia" = 28;
UPDATE "Dependencia" SET "vDependencia" = 'Régimen Estatal de Protección Social en Salud ', "vNombreCorto" = 'REPSSY' WHERE "iIdDependencia" = 29;
UPDATE "Dependencia" SET "vDependencia" = 'Sistema para el Desarrollo Integral de la Familia en Yucatán ', "vNombreCorto" = 'DIF Yucatán' WHERE "iIdDependencia" = 30;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de la Cultura y las Artes ', "vNombreCorto" = 'SEDECULTA' WHERE "iIdDependencia" = 31;
UPDATE "Dependencia" SET "vDependencia" = 'Casa de las Artesanías del Gobierno del Estado de Yucatán ', "vNombreCorto" = 'CAEY' WHERE "iIdDependencia" = 32;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela Superior de Artes de Yucatán ', "vNombreCorto" = 'ESAY' WHERE "iIdDependencia" = 33;
UPDATE "Dependencia" SET "vDependencia" = 'Fideicomiso Garante de la Orquesta Sinfónica de Yucatán ', "vNombreCorto" = 'FIGAROSY' WHERE "iIdDependencia" = 34;
UPDATE "Dependencia" SET "vDependencia" = 'Fideicomiso Público para la Administración del Palacio de la Música', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 35;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto del Deporte de Yucatán ', "vNombreCorto" = 'IDEY' WHERE "iIdDependencia" = 36;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Desarrollo Sustentable', "vNombreCorto" = 'SDS' WHERE "iIdDependencia" = 37;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Movilidad y Desarrollo Urbano Territorial ', "vNombreCorto" = 'IMDUT' WHERE "iIdDependencia" = 38;
UPDATE "Dependencia" SET "vDependencia" = 'Junta de Agua Potable y Alcantarillado de Yucatán ', "vNombreCorto" = 'JAPAY' WHERE "iIdDependencia" = 39;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de las Mujeres', "vNombreCorto" = 'SEMUJERES' WHERE "iIdDependencia" = 40;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto para la Inclusión de las Personas con Discapacidad ', "vNombreCorto" = 'IIPEDEY' WHERE "iIdDependencia" = 41;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Investigación, Innovación y Educación Superior ', "vNombreCorto" = 'SIIES' WHERE "iIdDependencia" = 42;
UPDATE "Dependencia" SET "vDependencia" = 'Consejo de Ciencia, Innovación y Tecnología del Estado de Yucatán ', "vNombreCorto" = 'CONCIYTEY' WHERE "iIdDependencia" = 43;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Tecnológico Superior de Motul ', "vNombreCorto" = 'ITSM' WHERE "iIdDependencia" = 44;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Tecnológico Superior de Progreso ', "vNombreCorto" = 'ITSP' WHERE "iIdDependencia" = 45;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Tecnológico Superior de Valladolid ', "vNombreCorto" = 'ITSVA' WHERE "iIdDependencia" = 46;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Tecnológico Superior del Sur del Estado de Yucatán ', "vNombreCorto" = 'ITSSY' WHERE "iIdDependencia" = 47;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad de Oriente ', "vNombreCorto" = 'UNO' WHERE "iIdDependencia" = 48;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Politécnica de Yucatán ', "vNombreCorto" = 'UPY' WHERE "iIdDependencia" = 49;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Tecnológica del Centro ', "vNombreCorto" = 'UTC' WHERE "iIdDependencia" = 50;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Tecnológica del Mayab ', "vNombreCorto" = 'UT del Mayab' WHERE "iIdDependencia" = 51;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Tecnológica del Poniente ', "vNombreCorto" = 'UTP' WHERE "iIdDependencia" = 52;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Tecnológica Metropolitana ', "vNombreCorto" = 'UTM' WHERE "iIdDependencia" = 53;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Tecnológica Regional del Sur ', "vNombreCorto" = 'UT Regional del Sur' WHERE "iIdDependencia" = 54;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela normal superior de Yucatán', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 55;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela normal de Dzidzantún', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 56;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela normal de Ticul', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 57;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela normal de Valladolid Juan de Dios Rodriguez Heredia', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 58;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela normal de educación preescolar', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 59;
UPDATE "Dependencia" SET "vDependencia" = 'Escuela normal de educación primaria Rodolfo Menéndez de la Peña', "vNombreCorto" = ' ' WHERE "iIdDependencia" = 60;
UPDATE "Dependencia" SET "vDependencia" = 'Fiscalía General del Estado ', "vNombreCorto" = 'FGE' WHERE "iIdDependencia" = 61;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Seguridad Pública ', "vNombreCorto" = 'SSP' WHERE "iIdDependencia" = 62;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría General de Gobierno ', "vNombreCorto" = 'SGG' WHERE "iIdDependencia" = 63;
UPDATE "Dependencia" SET "vDependencia" = 'Consejería Juridica ', "vNombreCorto" = 'CJ' WHERE "iIdDependencia" = 64;
UPDATE "Dependencia" SET "vDependencia" = 'Comisión Ejecutiva Estatal de Atención a Víctimas ', "vNombreCorto" = 'CEEAV' WHERE "iIdDependencia" = 65;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría Ejecutiva del Sistema Estatal Anticorrupción ', "vNombreCorto" = 'SESEAY' WHERE "iIdDependencia" = 66;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Seguridad Jurídica Patrimonial de Yucatán ', "vNombreCorto" = 'INSEJUPY' WHERE "iIdDependencia" = 67;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Desarrollo Regional Municipal ', "vNombreCorto" = 'INDERM' WHERE "iIdDependencia" = 68;
UPDATE "Dependencia" SET "vDependencia" = 'Centro Estatal de Prevención al Delito de Yucatán ', "vNombreCorto" = 'CEPREDEY' WHERE "iIdDependencia" = 69;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Administración y Finanzas', "vNombreCorto" = 'SAF' WHERE "iIdDependencia" = 70;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de la Contraloría General ', "vNombreCorto" = 'SECOGEY' WHERE "iIdDependencia" = 71;
UPDATE "Dependencia" SET "vDependencia" = 'Jefatura del Despacho del Gobernador ', "vNombreCorto" = 'JDG' WHERE "iIdDependencia" = 72;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría Técnica de Planeación y Evaluación ', "vNombreCorto" = 'SEPLAN' WHERE "iIdDependencia" = 73;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Seguridad Social de los Trabajadores del Estado de Yucatán ', "vNombreCorto" = 'ISSTEY' WHERE "iIdDependencia" = 74;
UPDATE "Dependencia" SET "vDependencia" = 'Fideicomiso Público para la Administración de la Reserva Territorial de Ucú ', "vNombreCorto" = 'Fidartu' WHERE "iIdDependencia" = 75;
UPDATE "Dependencia" SET "vDependencia" = 'Sistema Teleyucatán, S.A. de C.V. ', "vNombreCorto" = 'Trece TV' WHERE "iIdDependencia" = 76;
UPDATE "Dependencia" SET "vDependencia" = 'Agencia de Adminitración Fiscal de Yucatán', "vNombreCorto" = 'AAFY' WHERE "iIdDependencia" = 77;
UPDATE "Dependencia" SET "vDependencia" = 'XH-YUC 92.9 F.M. La Radio Yucateca ', "vNombreCorto" = 'IMER' WHERE "iIdDependencia" = 78;
UPDATE "Dependencia" SET "vDependencia" = 'Secretaría de Obras Públicas', "vNombreCorto" = 'SOP' WHERE "iIdDependencia" = 79;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Infraestructura Carretera de Yucatán ', "vNombreCorto" = 'INCAY' WHERE "iIdDependencia" = 80;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto para el Desarrollo y Certificación de la Infraestructura Física Educativa de Yucatán ', "vNombreCorto" = 'IDEFEY' WHERE "iIdDependencia" = 81;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto para la Construcción y Conservación de Obra Pública en Yucatán ', "vNombreCorto" = 'INCCOPY' WHERE "iIdDependencia" = 82;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto de Vivienda del Estado de Yucatán ', "vNombreCorto" = 'IVEY' WHERE "iIdDependencia" = 83;
UPDATE "Dependencia" SET "vDependencia" = 'Auditoría Superior del Estado de Yucatán', "vNombreCorto" = 'ASEY' WHERE "iIdDependencia" = 84;
UPDATE "Dependencia" SET "vDependencia" = 'Congreso del Estado de Yucatán', "vNombreCorto" = 'CEY' WHERE "iIdDependencia" = 85;
UPDATE "Dependencia" SET "vDependencia" = 'Comisión de Derechos Humanos del Estado de Yucatán', "vNombreCorto" = 'CODHEY' WHERE "iIdDependencia" = 86;
UPDATE "Dependencia" SET "vDependencia" = 'Consejo de la Judicatura del Poder Judicial del Estado de Yucatán', "vNombreCorto" = 'CONJUPOJ' WHERE "iIdDependencia" = 87;
UPDATE "Dependencia" SET "vDependencia" = 'Despacho del Gobernador', "vNombreCorto" = 'DG' WHERE "iIdDependencia" = 88;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Electoral y de Participación Ciudadana de Yucatán', "vNombreCorto" = 'IEPAC' WHERE "iIdDependencia" = 89;
UPDATE "Dependencia" SET "vDependencia" = 'Instituto Estatal de Acceso a la Información Pública', "vNombreCorto" = 'INAIP' WHERE "iIdDependencia" = 90;
UPDATE "Dependencia" SET "vDependencia" = 'Junta de Electrificación de Yucatán', "vNombreCorto" = 'JEDEY' WHERE "iIdDependencia" = 91;
UPDATE "Dependencia" SET "vDependencia" = 'Poder Judicial del Estado de Yucatán', "vNombreCorto" = 'PJEY' WHERE "iIdDependencia" = 92;
UPDATE "Dependencia" SET "vDependencia" = 'Sistema Tele Yucatán, S.A. de C.V.', "vNombreCorto" = 'STY' WHERE "iIdDependencia" = 93;
UPDATE "Dependencia" SET "vDependencia" = 'Tribunal Electoral del Estado de Yucatán', "vNombreCorto" = 'TEEY' WHERE "iIdDependencia" = 94;
UPDATE "Dependencia" SET "vDependencia" = 'Tribunal Electoral del Estado de Yucatán', "vNombreCorto" = 'TJAY' WHERE "iIdDependencia" = 95;
UPDATE "Dependencia" SET "vDependencia" = 'Tribunal de los Trabajadores al Servicio del Estado', "vNombreCorto" = 'TTSEY' WHERE "iIdDependencia" = 96;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Autónoma de Yucatán', "vNombreCorto" = 'UADY' WHERE "iIdDependencia" = 97;
UPDATE "Dependencia" SET "vDependencia" = 'Aeropuerto Internacional de Chichén Itzá', "vNombreCorto" = 'AICI' WHERE "iIdDependencia" = 98;
UPDATE "Dependencia" SET "vDependencia" = 'Centro Estatal de Capacitación, Investigación y Difusión Humanística de Yucatán', "vNombreCorto" = 'CECIDHY' WHERE "iIdDependencia" = 99;
UPDATE "Dependencia" SET "vDependencia" = 'Universidad Pedagógica Nacional', "vNombreCorto" = 'Upedagógica' WHERE "iIdDependencia" = 100;
UPDATE "Dependencia" SET "vDependencia" = 'Agencia de Administración Fiscal de Yucatán', "vNombreCorto" = 'AAFY' WHERE "iIdDependencia" = 101;
UPDATE "Dependencia" SET "vDependencia" = 'SOP', "vNombreCorto" = 'SOP' WHERE "iIdDependencia" = 102;
UPDATE "Dependencia" SET "vDependencia" = 'Dep1', "vNombreCorto" = 'Dependencia de prueba 1' WHERE "iIdDependencia" = 103;
